// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Use a fallback empty string so TypeScript infers a plain string rather than
  // the union `string | undefined`. In practice the .env file should always
  // provide a DATABASE_URL. If it's missing, Prisma will error at runtime.
  datasource: {
    url: process.env["DATABASE_URL"] || "",
  },
});
